## SVM Exercise

In [5]:
# import pandas
import pandas as pd
import numpy as np

from sklearn import svm
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [6]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)

* create X, y

In [8]:
X = irisdata.drop('Class', axis = 1)
y = irisdata['Class']

* import train_test_split and split data

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3)

* import SVC from sklearn and use Polynomial kernel

In [10]:
SVM = svm.SVC(kernel='poly')

* fit training data

In [12]:
SVM.fit(X_train,y_train)

SVC(kernel='poly')

* predict X_test

In [15]:
y_pred = SVM.predict(X_test)

* import confusion matrix from sklearn and print values

In [16]:
con_mat = metrics.confusion_matrix(y_test,y_pred)
con_mat

array([[16,  0,  0],
       [ 0, 12,  1],
       [ 0,  0, 16]])

In [17]:
metrics.accuracy_score(y_test,y_pred)

0.9777777777777777

* create SVC with rbf kernel

In [18]:
SVM_rbf = svm.SVC(kernel='rbf')

* fit training data

In [19]:
SVM_rbf.fit(X_train,y_train)

SVC()

* predict X_test

In [20]:
y_pred_rbf = SVM_rbf.predict(X_test)

* print confusion matrix

In [21]:
con_mat = metrics.confusion_matrix(y_test,y_pred_rbf)
con_mat

array([[16,  0,  0],
       [ 0, 12,  1],
       [ 0,  2, 14]])

* create SVC with sigmoid kernel

In [22]:
SVM_sigmoid = svm.SVC(kernel='sigmoid')

* fit training data

In [23]:
SVM_sigmoid.fit(X_train,y_train)

SVC(kernel='sigmoid')

* predict X_test

In [24]:
y_pred_sigmoid = SVM_sigmoid.predict(X_test)

In [25]:
con_mat = metrics.confusion_matrix(y_test,y_pred_sigmoid)
con_mat

array([[ 0, 16,  0],
       [ 0, 13,  0],
       [ 0, 16,  0]])

In [26]:
metrics.accuracy_score(y_test, y_pred_sigmoid)

0.28888888888888886

#### Q: Which kernel was the most accurate on the testing set?

In [ ]:
# polynomial -> radial bias function -> sigmoid