In [241]:
from pandas import DataFrame
import statsmodels.api as sm
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LassoCV
from sklearn.linear_model import RidgeCV
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

# Remove columns

## columns where: #Nan > 40%, not logical, rows where:  #Nan  > ~60%

## seperate into X (feature) and Y (Target)

In [242]:
X = pd.read_csv('X_linear_regression.csv', sep = ',')
y = X['Sale_price']
X.drop(['Unnamed: 0','Sale_price'], axis =1, inplace = True)

In [243]:
X

OverallQual  YearBuilt  YearRemodAdd  MasVnrArea  TotalBsmtSF  \
0             7.0     2003.0        2003.0       196.0        856.0   
1             6.0     1976.0        1976.0         0.0       1262.0   
2             7.0     2001.0        2002.0       162.0        920.0   
3             7.0     1915.0        1970.0         0.0        756.0   
4             8.0     2000.0        2000.0       350.0       1145.0   
...           ...        ...           ...         ...          ...   
1455          6.0     1999.0        2000.0         0.0        953.0   
1456          6.0     1978.0        1988.0       119.0       1542.0   
1457          7.0     1941.0        2006.0         0.0       1152.0   
1458          5.0     1950.0        1996.0         0.0       1078.0   
1459          5.0     1965.0        1965.0         0.0       1256.0   

      GrLivArea  FullBath  Fireplaces  GarageYrBlt  GarageCars  
0        1710.0       2.0         0.0       2003.0         2.0  
1        1262.0       2.0         1.0       1976.0         2.0  
2        1786.0       2.0         1.0       2001.0         2.0  
3        1717.0       1.0         1.0       1998.0         3.0  
4        2198.0       2.0         1.0       2000.0         3.0  
...         ...       ...         ...          ...         ...  
1455     1647.0       2.0         1.0       1999.0         2.0  
1456     2073.0       2.0         2.0       1978.0         2.0  
1457     2340.0       2.0         2.0       1941.0         1.0  
1458     1078.0       1.0         0.0       1950.0         1.0  
1459     1256.0       1.0         0.0       1965.0         1.0  

[1460 rows x 10 columns]

### Dropping columns

In [226]:
# R^2 = 0.963, durbin = 1.956
X.drop(['FullBath'], axis = 1, inplace = True)

In [227]:
# R^2 = 0.963, durbin = 1.957
X.drop(['FullBath','YearBuilt'], axis = 1, inplace = True)

In [247]:
# R^2 = 0.963, durbin = 1.959
X.drop(['FullBath','YearRemodAdd'], axis = 1, inplace = True)

In [244]:
# R^2 = 0.963, durbin = 1.956
X

OverallQual  YearBuilt  YearRemodAdd  MasVnrArea  TotalBsmtSF  \
0             7.0     2003.0        2003.0       196.0        856.0   
1             6.0     1976.0        1976.0         0.0       1262.0   
2             7.0     2001.0        2002.0       162.0        920.0   
3             7.0     1915.0        1970.0         0.0        756.0   
4             8.0     2000.0        2000.0       350.0       1145.0   
...           ...        ...           ...         ...          ...   
1455          6.0     1999.0        2000.0         0.0        953.0   
1456          6.0     1978.0        1988.0       119.0       1542.0   
1457          7.0     1941.0        2006.0         0.0       1152.0   
1458          5.0     1950.0        1996.0         0.0       1078.0   
1459          5.0     1965.0        1965.0         0.0       1256.0   

      GrLivArea  FullBath  Fireplaces  GarageYrBlt  GarageCars  
0        1710.0       2.0         0.0       2003.0         2.0  
1        1262.0       2.0         1.0       1976.0         2.0  
2        1786.0       2.0         1.0       2001.0         2.0  
3        1717.0       1.0         1.0       1998.0         3.0  
4        2198.0       2.0         1.0       2000.0         3.0  
...         ...       ...         ...          ...         ...  
1455     1647.0       2.0         1.0       1999.0         2.0  
1456     2073.0       2.0         2.0       1978.0         2.0  
1457     2340.0       2.0         2.0       1941.0         1.0  
1458     1078.0       1.0         0.0       1950.0         1.0  
1459     1256.0       1.0         0.0       1965.0         1.0  

[1460 rows x 10 columns]

# Statsmodel

In [248]:
lin_reg = sm.OLS(y,X)

In [249]:
model = lin_reg.fit()
print_model = model.summary()
print_model

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:             Sale_price   R-squared (uncentered):                   0.963
Model:                            OLS   Adj. R-squared (uncentered):              0.963
Method:                 Least Squares   F-statistic:                              4753.
Date:                Tue, 18 Aug 2020   Prob (F-statistic):                        0.00
Time:                        11:09:54   Log-Likelihood:                         -17464.
No. Observations:                1460   AIC:                                  3.494e+04
Df Residuals:                    1452   BIC:                                  3.499e+04
Df Model:                           8                                                  
Covariance Type:            nonrobust                                                  
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
OverallQual  2.166e+04   1086.989     19.925      0.000    1.95e+04    2.38e+04
YearBuilt     278.2684     52.538      5.297      0.000     175.210     381.327
MasVnrArea     29.6367      6.312      4.695      0.000      17.255      42.018
TotalBsmtSF    27.0027      2.840      9.508      0.000      21.432      32.573
GrLivArea      41.5676      2.565     16.207      0.000      36.537      46.599
Fireplaces   7662.7760   1780.684      4.303      0.000    4169.788    1.12e+04
GarageYrBlt  -323.2274     52.522     -6.154      0.000    -426.254    -220.200
GarageCars   2.214e+04   1842.568     12.016      0.000    1.85e+04    2.58e+04
==============================================================================
Omnibus:                      422.243   Durbin-Watson:                   1.959
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            36769.191
Skew:                          -0.278   Prob(JB):                         0.00
Kurtosis:                      27.579   Cond. No.                     6.45e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.45e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

### Ridge

In [232]:
ridge = Ridge(alpha=41)

In [233]:
ridge_res = ridge.fit(X,y)

In [234]:
ridge_res.score(X,y)

0.7778323108022814

In [235]:
ridge_res.coef_

array([1.82626380e+04, 4.67129752e+02, 3.79566820e+01, 2.97527496e+01,
       4.21705217e+01, 9.32409844e+03, 1.71401439e+01, 1.39572556e+04])

### Lasso

In [236]:
lasso = Lasso(random_state=0, alpha = 0.00001)

In [237]:
lasso_res = lasso.fit(X,y)

In [238]:
lasso_res.score(X,y)

0.7780054487802157

In [239]:
lasso_res.coef_

array([ 1.88070126e+04,  4.62525206e+02,  3.69453400e+01,  2.90181107e+01,
        4.08580013e+01,  9.87834842e+03, -1.66509692e+01,  1.56608232e+04])

## Gridsearch optimal alpha

### Lasso

In [146]:
alphas = np.logspace(-5, 50, 500)
parameter_candidates = [{'alpha':alphas}]
n_folds = 10

In [147]:
lasso = Lasso(random_state=0)

In [148]:
clf = GridSearchCV(estimator=lasso, param_grid=parameter_candidates, cv = n_folds)

In [149]:
clf.fit(X, y)

GridSearchCV(cv=10, estimator=Lasso(random_state=0),
             param_grid=[{'alpha': array([1.00000000e-05, 1.28890361e-05, 1.66127252e-05, 2.14122015e-05,
       2.75982639e-05, 3.55715021e-05, 4.58482375e-05, 5.90939590e-05,
       7.61664172e-05, 9.81711702e-05, 1.26533176e-04, 1.63089068e-04,
       2.10206088e-04, 2.70935387e-04, 3.49209598e-04, 4.50097513e-04,
       5.80132310e-04, 7.47734631e-04, 9...
       2.91695588e+47, 3.75967497e+47, 4.84585864e+47, 6.24584471e+47,
       8.05029181e+47, 1.03760502e+48, 1.33737286e+48, 1.72374471e+48,
       2.22174078e+48, 2.86360972e+48, 3.69091691e+48, 4.75723614e+48,
       6.13161884e+48, 7.90306568e+48, 1.01862899e+49, 1.31291459e+49,
       1.69222035e+49, 2.18110892e+49, 2.81123917e+49, 3.62341632e+49,
       4.67023439e+49, 6.01948197e+49, 7.75853206e+49, 1.00000000e+50])}])

In [150]:
clf.best_score_

0.7770096882979123

In [151]:
clf.best_params_

{'alpha': 1e-05}

## Ridge

In [118]:
alphas = np.logspace(-5, 50, 500)
parameter_candidates = [{'alpha':alphas}]
n_folds = 10

In [119]:
ridge = Ridge(random_state=0)

In [120]:
clf = GridSearchCV(estimator=ridge, param_grid=parameter_candidates, cv = n_folds)

In [121]:
clf.fit(X, y)

GridSearchCV(cv=10, estimator=Ridge(random_state=0),
             param_grid=[{'alpha': array([1.00000000e-05, 1.28890361e-05, 1.66127252e-05, 2.14122015e-05,
       2.75982639e-05, 3.55715021e-05, 4.58482375e-05, 5.90939590e-05,
       7.61664172e-05, 9.81711702e-05, 1.26533176e-04, 1.63089068e-04,
       2.10206088e-04, 2.70935387e-04, 3.49209598e-04, 4.50097513e-04,
       5.80132310e-04, 7.47734631e-04, 9...
       2.91695588e+47, 3.75967497e+47, 4.84585864e+47, 6.24584471e+47,
       8.05029181e+47, 1.03760502e+48, 1.33737286e+48, 1.72374471e+48,
       2.22174078e+48, 2.86360972e+48, 3.69091691e+48, 4.75723614e+48,
       6.13161884e+48, 7.90306568e+48, 1.01862899e+49, 1.31291459e+49,
       1.69222035e+49, 2.18110892e+49, 2.81123917e+49, 3.62341632e+49,
       4.67023439e+49, 6.01948197e+49, 7.75853206e+49, 1.00000000e+50])}])

In [122]:
clf.best_score_

0.7772730299825905

In [123]:
clf.best_params_

{'alpha': 41.04180502904709}

# Sklearn

In [67]:
X = pd.read_csv('X_linear_regression.csv', sep = ',')
y = X['Sale_price']
X.drop(['Unnamed: 0','Sale_price'], axis =1, inplace = True)

In [68]:
X.head()

OverallQual  YearBuilt  YearRemodAdd  MasVnrArea  TotalBsmtSF  GrLivArea  \
0          7.0     2003.0        2003.0       196.0        856.0     1710.0   
1          6.0     1976.0        1976.0         0.0       1262.0     1262.0   
2          7.0     2001.0        2002.0       162.0        920.0     1786.0   
3          7.0     1915.0        1970.0         0.0        756.0     1717.0   
4          8.0     2000.0        2000.0       350.0       1145.0     2198.0   

   FullBath  Fireplaces  GarageYrBlt  GarageCars  
0       2.0         0.0       2003.0         2.0  
1       2.0         1.0       1976.0         2.0  
2       2.0         1.0       2001.0         2.0  
3       1.0         1.0       1998.0         3.0  
4       2.0         1.0       2000.0         3.0

In [69]:
regressor = LinearRegression()
regressor.fit(X, y)

LinearRegression()

In [70]:
regressor.coef_

array([17849.54532241,   305.75745503,   392.74217046,    31.38657422,
          26.31029415,    46.51074854, -4636.91104601,  9398.44028877,
        -187.31394272, 16937.58077891])

In [71]:
regressor.score(X,y)

0.7822149409543702

In [72]:
regressor.intercept_

-1070411.3757089768