In [54]:
import pandas as pd
import numpy as np
import random

from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

In [3]:
y_true = np.random.normal(0,1,10)
errors = np.random.normal(0,0.02,10)
y_pred = y_true + errors

In [4]:
y_true

array([-1.96689432,  0.08350214,  1.37355236,  0.31560434, -0.47807087,
       -0.40833517, -0.02822629, -1.56583453,  0.9718557 , -1.16292898])

In [5]:
errors

array([-0.00114079, -0.00757745, -0.01350854,  0.00266274, -0.03697711,
       -0.00264919, -0.03598164, -0.0110066 , -0.01224724, -0.01050564])

In [6]:
y_pred

array([-1.96803511,  0.0759247 ,  1.36004383,  0.31826708, -0.51504798,
       -0.41098436, -0.06420793, -1.57684113,  0.95960846, -1.17343462])

# MSE (mean squared error)

In [31]:
# compute MSE
MSE = mean_squared_error(y_true,y_pred)  

# print MSE
print(MSE)

0.000329880185315516


In [36]:
my_MSE = 0
for i in range(len(y_true)):
    e = (y_pred[i] - y_true[i])**2
    my_MSE += e
MSE = my_MSE / len(y_true)
print(MSE)

0.000329880185315516


In [37]:
# RMSE by Numpy
RMSE = np.sqrt(my_MSE/len(y_true))
print(RMSE)

# RMSE by sklearn
RMSE = mean_squared_error(y_true,y_pred,squared=False)
print(RMSE)

0.01816260403454075
0.01816260403454075


# Classification model evaluation

In [38]:
# ground truth
y_true = [1,1,0,1,0,0,1,0,0,1]

# simulate probabilites of positive class
y_proba = [0.9,0.7,0.2,0.99,0.7,0.1,0.5,0.2,0.4,0.6]

# set the threshold to predict positive class
thres = 0.5

In [39]:
# class predictions
y_pred = [int(value > thres) for value in y_proba]

In [40]:
y_pred

[1, 1, 0, 1, 1, 0, 0, 0, 0, 1]

In [48]:
# compute accuracy
accuracy = accuracy_score(y_true,y_pred)

# print accuracy
print(accuracy)

0.8


In [51]:
correct = 0
for i in range(len(y_true)):
    if (y_true[i] == y_pred[i]):
        correct += 1
print(correct/len(y_true))

0.8


In [53]:
# compute F1-score
f1_score = f1_score(y_true,y_pred)

# print F1-score
print(f1_score)

0.8000000000000002


In [57]:
# compute AUC-score
# used y_proba, passing y_pred would yield inaccurate score
auc = roc_auc_score(y_true,y_proba)

# print AUC-score
print(auc)

0.9
