In [110]:
# import numpy
import numpy as np


**Task:** create matrix (2x2) matrix 'A'


In [33]:
A = np.matrix([[1,2],[4,3]])
A

matrix([[1, 2],
        [4, 3]])

In [34]:
A[0,1]

2

**Task:**

In [35]:
"""
Define function 'shape_2x2' which checks if matrix has shape (2x2)

PARAMS:
    matrix (numpy.ndarray) - matrix to check
RETURN:
    True (bool) - if matrix has shape 2x2
    False (bool) - if matrix has not shape 2x2

"""
def shape_2x2(matrix):
    if matrix.shape[0] == 2 and matrix.shape[1] == 2:
        return(True)
    else:
        return(False)

In [36]:
shape_2x2(A)

True

**Task:**

In [37]:
"""
Define function 'determinant_2x2' which computes determinant of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to compute determinant
RETURN:
    det (float) - matrix determinant

Do not forget to check the shape of  the input matrix.
"""
def determinant_2x2(matrix):
    ad = A[0,0] * A[1,1]
    bc = A[0,1] * A[1,0]
    det = ad - bc
    return(det)

**Task:** call the function 'determinant_2x2' with matrix 'A' 

In [38]:
determinant_2x2(A)

-5

**Task:** compute the eigenvectors, eigenvalues of matrix 'A' with numpy

In [62]:
eig_val, eig_vec = np.linalg.eig(A)

**Task:** print eigenvalues

In [63]:
eig_val

array([-1.,  5.])

**Task:** print eigenvectors

In [64]:
eig_vec

matrix([[-0.70710678, -0.4472136 ],
        [ 0.70710678, -0.89442719]])

**Task:**

In [145]:
"""
Define function 'eig_2x2' which computes eigenvectors and eigenvalues of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to perform decomposition
RETURN:
    eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

Do not use np.linalg.eig function!
Use 'shape_2x2' and 'determinant_2x2' functions. 
Be carefull, eigenvalues and eigenvectors could contain complex numbers.

How to compute eigenvalues of 2x2 matrix:
https://yutsumura.com/express-the-eigenvalues-of-a-2-by-2-matrix-in-terms-of-the-trace-and-determinant/
"""

def eig_2x2(matrix):
    if shape_2x2(matrix):
        eig_val = []
        eig_vec = []
        
        a = 1
        b = -(matrix[0,0] + matrix[1,1])
        c = determinant_2x2(matrix)
    
        eig_val.append( (-b + np.sqrt(b**2-(4*a*c)) )/ (2*a)  )
        eig_val.append( (-b - np.sqrt(b**2-(4*a*c)) )/ (2*a)  )
        
        for i in range(len(eig_val)):
            if i == 0:
                x1 = (eig_val[i]-matrix[i,0])/matrix[i,1]
                x2 = 1
                eig_vec.append([x2,x1])
            else:
                x2 = (eig_val[i]-matrix[i,1])/matrix[i,0]
                x1 = 1
                eig_vec.append([x2,x1])
            
        return(eig_val,eig_vec)
    else:
        return('matrix is not 2x2')

In [146]:
my_val, my_vec  = eig_2x2(A)

In [147]:
my_vec[0]

[1, 2.0]

**Task:** call the function 'deig_2x2' with matrix 'A' 

In [136]:
eig_2x2(A)

([5.0, -1.0], [[2.0, 1], [1, -1.0]])

**Task:** compare the result with numpy function (to comparison use np.allclose function)

In [150]:
val, vec = np.linalg.eig(A)
print(val)
print(vec)
my_matrix = np.transpose(np.matrix([my_vec[1],my_vec[0]]))
print(my_matrix)
np.allclose(vec,my_matrix)

[-1.  5.]
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]
[[-1.  1.]
 [ 1.  2.]]


False

**Task:** define matrix B = np.array([[0,1],[-1,0]]) 

In [151]:
B = np.array([[0,1],[-1,0]])
B

array([[ 0,  1],
       [-1,  0]])

**Task:** compute eigenvalues and eigevectors of matrix 'B' with numpy and with 'eig_2x2' function

In [154]:
np_val, np_vec = np.linalg.eig(B)
B_val, B_vec = eig_2x2(B)

**Task:** compare the results with numpy function (to comparison use np.allclose function)

In [155]:
print(np_val, B_val)
print(np_vec)
print(B_vec)

[0.+1.j 0.-1.j] [2.23606797749979, -2.23606797749979]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        +0.70710678j 0.        -0.70710678j]]
[[1, 2.23606797749979], [2.23606797749979, 1]]


**Task:** print eigenvalues and eigenvectors and try to explain why the solutions is different

In [ ]:
# becasue technically there are no eigenvalues or vectors inthe real space.
# However there are with imaginary numbers