In [54]:
# import numpy
import numpy as np
from pprint import pprint

**Task:** generate random matrix 'A' with shape 150x50, use 'np.random.rand' function

In [6]:
A = np.random.rand(150,50)

**Task:** check the shape of 'A'

In [8]:
A.shape

(150, 50)

**Task:** decompose matrix 'A' with SVD using numpy (decompose into matrices U,D,V)

In [26]:
U,D,V = np.linalg.svd(A, False)

**Task:** check the shapes of matrices U,D,V

In [27]:
U.shape

(150, 50)

In [28]:
D.shape

(50,)

In [29]:
V.shape

(50, 50)

**Task:** reconstruct matrix 'A' from matrices U,D,V

In [46]:
A_rec = (U.dot(np.diag(D))).dot(V)
A_rec.shape

(150, 50)

**Task:** compare matrices 'A' and 'A_rec' with np.allclose function

In [63]:
np.allclose(A,A_rec)

True

**Task:** Reduce dimnesion of matrix 'A' to shape 150x20 with SVD (try both equations)

In [64]:
U_reduced = U[:,:20]
D_reduced = np.diag(D[:20])
V_reduced = V[:20,:]

In [78]:
print(U_reduced.shape)
print(D_reduced.shape)
print(V_reduced.shape)

(150, 20)
(20, 20)
(20, 50)


In [70]:
red1 = U_reduced.dot(D_reduced)
red2 = A.dot(V_reduced.T)

In [71]:
np.allclose(red1, red2)

True

**Task:** print shapes

In [72]:
print(red1.shape)
print(red2.shape)

(150, 20)
(150, 20)


**Task:** compare these two results with np.allclose function

In [73]:
np.allclose(red1, red2)

True

**Task:** filter the noise from matrix 'A' with 20 largest singular vectors (keep the shape (150x50))

In [81]:
A_filt = (U_reduced.dot(D_reduced).dot(V_reduced))

**Task:** check the shape

In [82]:
A_filt.shape

(150, 50)

**Task:**

In [322]:
A = np.random.rand(4,4)
AAT = A.dot(A.T)
ATA = A.T.dot(A)

In [339]:
A

array([[0.99411568, 0.36363072, 0.55088268, 0.62054459],
       [0.52202272, 0.70133785, 0.61773076, 0.89574866],
       [0.92987223, 0.35527503, 0.54515041, 0.71416747],
       [0.18312325, 0.45892707, 0.11008892, 0.56283172]])

In [330]:
AAT

array([[1.80904058, 1.6701281 , 1.79707615, 0.75883393],
       [1.6701281 , 1.94833944, 1.71105298, 0.98961849],
       [1.79707615, 1.71105298, 1.79810685, 0.79529768],
       [0.75883393, 0.98961849, 0.79529768, 0.5730473 ]])

In [341]:
AAT2 = np.matmul(A, A.T)
AAT2

array([[1.80904058, 1.6701281 , 1.79707615, 0.75883393],
       [1.6701281 , 1.94833944, 1.71105298, 0.98961849],
       [1.79707615, 1.71105298, 1.79810685, 0.79529768],
       [0.75883393, 0.98961849, 0.79529768, 0.5730473 ]])

In [331]:
ATA

array([[2.15897019, 1.14200588, 1.39719066, 1.85164632],
       [1.14200588, 0.96093647, 0.87775693, 1.36589609],
       [1.39719066, 0.87775693, 0.99437155, 1.34646898],
       [1.85164632, 1.36589609, 1.34646898, 2.01425596]])

In [ ]:
t1 = [[2,2],[3,3]]

In [334]:
"""
Define function 'SVD' which perform singular values decomposition
PARAMS:
    A (numpy.ndarray) - matrix to decompose
RETURN:
    U (numpy.ndarray) - left singular vectors
    SV (numpy.ndarray) - singular values
    V (numpy.ndarray) - right singular vectors
"""
def SVD(matrix):
    # A and A tranposed
    
    AAT = np.matmul(matrix, matrix.T)
    ATA = np.matmul(matrix.T, matrix)
    
    #AAT = matrix.dot(matrix.T)
    #ATA = matrix.T.dot(matrix)
    
    # eigenvalue and eigenvector 
    U_eig_val, U_eig_vec = np.linalg.eig(AAT)
    V_eig_val, V_eig_vec = np.linalg.eig(ATA)
    
    
    # arranging eigenvalue in order (largest to smallest)
    U_idx = np.array([(idx, val) for idx, val in enumerate(U_eig_val)])
    V_idx = np.array([(idx, val) for idx, val in enumerate(V_eig_val)])
    
    U_idx = sorted(U_idx, key=lambda x: x[1], reverse=True)
    V_idx = sorted(V_idx, key=lambda x: x[1], reverse=True)
    
    
    # Aranging eigen vectors with respect to eigenvalues
    U = np.array([U_eig_vec[:,int(x[0])] for x in U_idx]).T
    U = U[:, :min(A.shape)]
    
    D = np.array([x[1] for x in V_idx])
    
    V = np.array([V_eig_vec[:,int(x[0])] for x in V_idx])
    
    print(U,'\n')
    print(D,'\n')
    print(V,'\n')
    
    return(U,D,V)

In [335]:
U,D,V = SVD(A)

[[ 0.5478934   0.49043579  0.10130285 -0.670092  ]
 [ 0.56481553 -0.54609888 -0.61788423 -0.03128103]
 [ 0.55263535  0.35849909  0.15100697  0.73706816]
 [ 0.27457314 -0.57682506  0.7649534  -0.08202885]] 

[5.72366617e+00 3.70484567e-01 3.11814433e-02 3.20199554e-03] 

[[ 0.58671882  0.38358839  0.41055767  0.58314952]
 [ 0.70678532 -0.56190492  0.10640233 -0.41640836]
 [-0.33216785 -0.0464262   0.90238579 -0.27057164]
 [-0.21419631 -0.73141466  0.07629436  0.64290878]] 



In [336]:
x,y,z = np.linalg.svd(A, False)
x

array([[-0.5478934 ,  0.49043579,  0.10130285, -0.670092  ],
       [-0.56481553, -0.54609888, -0.61788423, -0.03128103],
       [-0.55263535,  0.35849909,  0.15100697,  0.73706816],
       [-0.27457314, -0.57682506,  0.7649534 , -0.08202885]])

In [337]:
y

array([2.39241848, 0.60867443, 0.17658268, 0.05658618])

In [338]:
z

array([[-0.58671882, -0.38358839, -0.41055767, -0.58314952],
       [ 0.70678532, -0.56190492,  0.10640233, -0.41640836],
       [ 0.33216785,  0.0464262 , -0.90238579,  0.27057164],
       [-0.21419631, -0.73141466,  0.07629436,  0.64290878]])

In [313]:
np.allclose(U, x)

False

In [314]:
np.allclose(V, z)

False

**Task:** # call the function 'SVD' with matrix 'A' 

In [216]:
U_eig_val, U_eig_vec = np.linalg.eig(AAT)
U_eig_val

array([ 3.39974821e+00,  5.29271033e-01,  3.43097763e-01,  7.27494967e-17,
       -2.57003893e-17])

In [217]:
U_eig_val, U_eig_vec = np.linalg.eig(AAT)
U_eig_vec

array([[ 0.56479085,  0.37587193, -0.23542892,  0.00735279, -0.66320893],
       [ 0.39048665,  0.20450582,  0.88616406, -0.06564977,  0.1020958 ],
       [ 0.5381287 , -0.64612118, -0.14420958, -0.50490709, -0.02242584],
       [ 0.3918768 ,  0.46273252, -0.37063459,  0.11187338,  0.6968749 ],
       [ 0.29220121, -0.43046915,  0.03346759,  0.85334004,  0.25217616]])

In [203]:
U_idx = np.array([(idx, val) for idx, val in enumerate(U_eig_val)])
U_idx = sorted(U_idx, key=lambda x: x[1], reverse=True)
U_idx

[array([0.        , 4.90656754]),
 array([1.       , 0.4486534]),
 array([2.        , 0.28615899]),
 array([3.00000000e+00, 2.67598063e-16]),
 array([4.00000000e+00, 1.41686863e-17])]

In [218]:
U_eig_vec[:,1]

array([ 0.37587193,  0.20450582, -0.64612118,  0.46273252, -0.43046915])

In [220]:
np.array([U_eig_vec[:,int(x[0])] for x in U_idx])

array([[ 0.56479085,  0.39048665,  0.5381287 ,  0.3918768 ,  0.29220121],
       [ 0.37587193,  0.20450582, -0.64612118,  0.46273252, -0.43046915],
       [-0.23542892,  0.88616406, -0.14420958, -0.37063459,  0.03346759],
       [ 0.00735279, -0.06564977, -0.50490709,  0.11187338,  0.85334004],
       [-0.66320893,  0.1020958 , -0.02242584,  0.6968749 ,  0.25217616]])

In [226]:
x,y,z = np.linalg.svd(A, False)
x

array([[-0.56479085,  0.37587193,  0.23542892],
       [-0.39048665,  0.20450582, -0.88616406],
       [-0.5381287 , -0.64612118,  0.14420958],
       [-0.3918768 ,  0.46273252,  0.37063459],
       [-0.29220121, -0.43046915, -0.03346759]])

In [224]:
U_eig_val, U_eig_vec = np.linalg.eig(AAT)

In [225]:
U_eig_vec

array([[ 0.56479085,  0.37587193, -0.23542892,  0.00735279, -0.66320893],
       [ 0.39048665,  0.20450582,  0.88616406, -0.06564977,  0.1020958 ],
       [ 0.5381287 , -0.64612118, -0.14420958, -0.50490709, -0.02242584],
       [ 0.3918768 ,  0.46273252, -0.37063459,  0.11187338,  0.6968749 ],
       [ 0.29220121, -0.43046915,  0.03346759,  0.85334004,  0.25217616]])

In [179]:
V_eig_val, V_eig_vec = np.linalg.eig(ATA)

In [180]:
V_eig_vec

array([[-0.79201341, -0.45919951,  0.40230655],
       [-0.4137184 , -0.08088618, -0.90680456],
       [-0.44894525,  0.884643  ,  0.12591635]])

In [181]:
V_eig_val

array([2.08284717, 0.09877817, 0.51127306])

In [150]:
idx = [(idx,value) for idx,value in enumerate(V_eig_val)]
idx = sorted(idx, key=lambda x: x[1], reverse=True)
idx

[(0, 12.62417966872682),
 (1, 1.5210589016126461),
 (4, 0.7567546276203776),
 (3, 0.6541921239008711),
 (2, 0.35536729292113617)]

In [ ]:
EV = np.array([tpl[1] for tpl in EVV_idx])
U = np.array([U[:,tpl[0]] for tpl in EVU_idx]).T
V = np.array([V[:,tpl[0]] for tpl in EVV_idx])

In [140]:
V = np.array([V_eig_vec[:,tpl[0]] for tpl in idx])
V

array([[-0.53133699, -0.38455329, -0.44810938, -0.4682673 , -0.3869412 ],
       [-0.2087068 , -0.213438  ,  0.47475077,  0.50190093, -0.65847768],
       [ 0.1281902 ,  0.11320962,  0.64789484, -0.72432291, -0.1622943 ],
       [-0.68659746, -0.16655116,  0.38146786,  0.06080566,  0.59298363],
       [-0.43159434,  0.87521842, -0.09232678,  0.02191291, -0.19676035]])

In [133]:
test = np.array([i[1] for i in idx])
np.diag(test)

array([[12.62417967,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.5210589 ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.35536729,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.65419212,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.75675463]])